services:
  app:
    restart: unless-stopped
  websocket:
    restart: unless-stopped
  deploy-worker:
    restart: unless-stopped
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
